const CONFIG={GITHUB_OWNER:'vonzippen',GITHUB_REPO:'vonzippen',GITHUB_BRANCH:'main',GITHUB_DIR:'images/on-stage',DRIVE_FOLDER_ID:'1_lezjsTrEVMUnefn5aQPIAUQHhGH7W6F',GITHUB_TOKEN_PROPERTY:'GITHUB_TOKEN',SYNC_STATE_PROPERTY:'SYNC_STATE'};
function doGet(){return HtmlService.createHtmlOutputFromFile('Index').setTitle('Von Zippen — On Stage Sync').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)}
function setGithubToken(t){if(!t||!t.trim())throw Error('GitHub token is empty.');PropertiesService.getScriptProperties().setProperty(CONFIG.GITHUB_TOKEN_PROPERTY,t.trim());return'GitHub token saved.'}
function getStatus(){return{driveConfigured:!!CONFIG.DRIVE_FOLDER_ID,githubConfigured:!!PropertiesService.getScriptProperties().getProperty(CONFIG.GITHUB_TOKEN_PROPERTY),syncing:!!PropertiesService.getScriptProperties().getProperty(CONFIG.SYNC_STATE_PROPERTY)}}
function startSync(){const t=PropertiesService.getScriptProperties().getProperty(CONFIG.GITHUB_TOKEN_PROPERTY);if(!t)throw Error('GitHub token is not configured.');const f=DriveApp.getFolderById(CONFIG.DRIVE_FOLDER_ID),items=[],it=f.getFiles();while(it.hasNext()){const x=it.next();if(/^image\/(jpeg|png|webp|gif)$/i.test(x.getMimeType()))items.push({id:x.getId(),name:cleanName(x.getName())})}items.sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'}));const gh={};listGithubFiles(t).forEach(x=>gh[x.name]={sha:x.sha});saveState({index:0,items:items,githubByName:gh,remainingDeletes:null,deleteIndex:0,manifest:[],added:0,updated:0,skipped:0,removed:0});return{total:items.length}}
function syncNext(){const t=PropertiesService.getScriptProperties().getProperty(CONFIG.GITHUB_TOKEN_PROPERTY),raw=PropertiesService.getScriptProperties().getProperty(CONFIG.SYNC_STATE_PROPERTY);if(!t)throw Error('GitHub token is not configured.');if(!raw)throw Error('No sync in progress. Press SYNC NOW first.');const s=JSON.parse(raw);if(s.index<s.items.length){const item=s.items[s.index],old=s.githubByName[item.name]||null,blob=DriveApp.getFileById(item.id).getBlob(),sha=gitBlobSha1(blob.getBytes());if(old&&old.sha===sha)s.skipped++;else{putGithubFile(t,item.name,blob,old?old.sha:null,old?'Update On Stage photo':'Add On Stage photo');old?s.updated++:s.added++}s.manifest.push(item.name);delete s.githubByName[item.name];s.index++;saveState(s);return progress(s)}if(s.remainingDeletes===null){s.remainingDeletes=Object.keys(s.githubByName);s.deleteIndex=0}if(s.deleteIndex<s.remainingDeletes.length){const n=s.remainingDeletes[s.deleteIndex],e=s.githubByName[n];deleteGithubFile(t,n,e.sha);s.removed++;s.deleteIndex++;saveState(s);return progress(s)}putGithubText(t,'images/on-stage.json',JSON.stringify({images:s.manifest},null,2)+'\n',getGithubFileSha(t,'images/on-stage.json'),'Update On Stage image manifest');const r={done:true,processed:s.items.length,total:s.items.length,added:s.added,updated:s.updated,skipped:s.skipped,removed:s.removed};PropertiesService.getScriptProperties().deleteProperty(CONFIG.SYNC_STATE_PROPERTY);return r}
function syncNextChunk(){return syncNext()}
function progress(s){return{done:false,processed:s.index,total:s.items.length,uploaded:s.index,uploadTotal:s.items.length,added:s.added,updated:s.updated,skipped:s.skipped,removed:s.removed}}
function gitBlobSha1(b){const h=Utilities.newBlob('blob '+b.length+'\0').getBytes();return hex(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_1,h.concat(b)))}
function hex(a){return a.map(b=>{b=b<0?b+256:b;return('0'+b.toString(16)).slice(-2)}).join('')}
function saveState(s){PropertiesService.getScriptProperties().setProperty(CONFIG.SYNC_STATE_PROPERTY,JSON.stringify(s))}
function cancelSync(){PropertiesService.getScriptProperties().deleteProperty(CONFIG.SYNC_STATE_PROPERTY);return'Sync cancelled.'}
function cleanName(n){return n.trim().replace(/[\\/:*?"<>|]/g,'-')}
function githubUrl(p){return'https://api.github.com/repos/'+CONFIG.GITHUB_OWNER+'/'+CONFIG.GITHUB_REPO+'/contents/'+p.split('/').map(encodeURIComponent).join('/')+'?ref='+encodeURIComponent(CONFIG.GITHUB_BRANCH)}
function githubRequest(u,t,o){const b={method:'get',muteHttpExceptions:true,headers:{Authorization:'Bearer '+t,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}};Object.assign(b,o||{});const r=UrlFetchApp.fetch(u,b),c=r.getResponseCode(),x=r.getContentText();if(c<200||c>=300)throw Error('GitHub API '+c+': '+x.slice(0,500));return x?JSON.parse(x):{}}
function listGithubFiles(t){try{const d=githubRequest(githubUrl(CONFIG.GITHUB_DIR),t);return Array.isArray(d)?d.filter(x=>x.type==='file'):[]}catch(e){if(String(e).indexOf('404')>=0)return[];throw e}}
function getGithubFileSha(t,p){try{return githubRequest(githubUrl(p),t).sha||null}catch(e){if(String(e).indexOf('404')>=0)return null;throw e}}
function putGithubFile(t,n,b,sha,msg){const p=CONFIG.GITHUB_DIR+'/'+encodeURIComponent(n).replace(/%2F/g,'/'),u='https://api.github.com/repos/'+CONFIG.GITHUB_OWNER+'/'+CONFIG.GITHUB_REPO+'/contents/'+p+'?ref='+encodeURIComponent(CONFIG.GITHUB_BRANCH),q={message:msg,content:Utilities.base64Encode(b.getBytes()),branch:CONFIG.GITHUB_BRANCH};if(sha)q.sha=sha;githubRequest(u,t,{method:'put',contentType:'application/json',payload:JSON.stringify(q)})}
function putGithubText(t,p,txt,sha,msg){const u='https://api.github.com/repos/'+CONFIG.GITHUB_OWNER+'/'+CONFIG.GITHUB_REPO+'/contents/'+p+'?ref='+encodeURIComponent(CONFIG.GITHUB_BRANCH),q={message:msg,content:Utilities.base64Encode(txt,Utilities.Charset.UTF_8),branch:CONFIG.GITHUB_BRANCH};if(sha)q.sha=sha;githubRequest(u,t,{method:'put',contentType:'application/json',payload:JSON.stringify(q)})}
function deleteGithubFile(t,n,sha){const p=CONFIG.GITHUB_DIR+'/'+encodeURIComponent(n).replace(/%2F/g,'/'),u='https://api.github.com/repos/'+CONFIG.GITHUB_OWNER+'/'+CONFIG.GITHUB_REPO+'/contents/'+p+'?ref='+encodeURIComponent(CONFIG.GITHUB_BRANCH);githubRequest(u,t,{method:'delete',contentType:'application/json',payload:JSON.stringify({message:'Remove deleted On Stage photo',sha:sha,branch:CONFIG.GITHUB_BRANCH})})}
