const CONFIG={GITHUB_OWNER:'vonzippen',GITHUB_REPO:'vonzippen',GITHUB_BRANCH:'main',GITHUB_DIR:'images/on-stage',DRIVE_FOLDER_ID:'1_lezjsTrEVMUnefn5aQPIAUQHhGH7W6F',GITHUB_TOKEN_PROPERTY:'GITHUB_TOKEN',SYNC_STATE_PROPERTY:'SYNC_STATE'};
function doGet(){return HtmlService.createHtmlOutputFromFile('Index').setTitle('Von Zippen — On Stage Sync').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL)}
function setGithubToken(t){PropertiesService.getScriptProperties().setProperty(CONFIG.GITHUB_TOKEN_PROPERTY,t.trim());return'GitHub token saved.'}
function getStatus(){return{driveConfigured:!!CONFIG.DRIVE_FOLDER_ID,githubConfigured:!!PropertiesService.getScriptProperties().getProperty(CONFIG.GITHUB_TOKEN_PROPERTY),syncing:!!PropertiesService.getScriptProperties().getProperty(CONFIG.SYNC_STATE_PROPERTY)}}
function startSync(){const t=PropertiesService.getScriptProperties().getProperty(CONFIG.GITHUB_TOKEN_PROPERTY);if(!t)throw Error('GitHub token is not configured.');const f=DriveApp.getFolderById(CONFIG.DRIVE_FOLDER_ID),items=[],it=f.getFiles();while(it.hasNext()){const x=it.next();if(/^image\/(jpeg|png|webp|gif)$/i.test(x.getMimeType()))items.push({id:x.getId(),name:cleanName(x.getName())})}items.sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true,sensitivity:'base'}));const gb={};listGithubFiles(t).forEach(x=>gb[x.name]={sha:x.sha});PropertiesService.getScriptProperties().setProperty(CONFIG.SYNC_STATE_PROPERTY,JSON.stringify({index:0,items,githubByName:gb,manifest:[],added:0,updated:0,removed:0,skipped:0}));return{total:items.length}}
function syncBatch(){const t=PropertiesService.getScriptProperties().getProperty(CONFIG.GITHUB_TOKEN_PROPERTY),r=PropertiesService.getScriptProperties().getProperty(CONFIG.SYNC_STATE_PROPERTY);if(!t)throw Error('GitHub token is not configured.');if(!r)throw Error('No sync in progress. Press SYNC NOW first.');const s=JSON.parse(r),end=Math.min(s.index+2,s.items.length);for(let i=s.index;i<end;i++){const item=s.items[i],existing=s.githubByName[item.name]||null,file=DriveApp.getFileById(item.id);putGithubFile(t,item.name,file.getBlob(),existing?existing.sha:null,existing?'Update On Stage photo':'Add On Stage photo');if(existing)s.updated++;else s.added++;s.manifest.push(item.name);delete s.githubByName[item.name]}s.index=end;if(s.index<s.items.length){PropertiesService.getScriptProperties().setProperty(CONFIG.SYNC_STATE_PROPERTY,JSON.stringify(s));return{done:false,processed:s.index,total:s.items.length,added:s.added,updated:s.updated,removed:s.removed,skipped:s.skipped}}Object.keys(s.githubByName).forEach(name=>{deleteGithubFile(t,name,s.githubByName[name].sha);s.removed++});putGithubText(t,'images/on-stage.json',JSON.stringify({images:s.manifest},null,2)+'\n',getGithubFileSha(t,'images/on-stage.json'),'Update On Stage image manifest');PropertiesService.getScriptProperties().deleteProperty(CONFIG.SYNC_STATE_PROPERTY);return{done:true,processed:s.index,total:s.items.length,added:s.added,updated:s.updated,removed:s.removed,skipped:s.skipped}}
function cancelSync(){PropertiesService.getScriptProperties().deleteProperty(CONFIG.SYNC_STATE_PROPERTY);return'Sync cancelled.'}
function cleanName(n){return n.trim().replace(/[\\/:*?"<>|]/g,'-')}
function githubUrl(p){return'https://api.github.com/repos/'+CONFIG.GITHUB_OWNER+'/'+CONFIG.GITHUB_REPO+'/contents/'+p.split('/').map(encodeURIComponent).join('/')+'?ref='+encodeURIComponent(CONFIG.GITHUB_BRANCH)}
function githubRequest(u,t,o){const b={method:'get',muteHttpExceptions:true,headers:{Authorization:'Bearer '+t,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}};Object.assign(b,o||{});const r=UrlFetchApp.fetch(u,b),c=r.getResponseCode(),x=r.getContentText();if(c<200||c>=300)throw Error('GitHub API '+c+': '+x.slice(0,500));return x?JSON.parse(x):{}}
function listGithubFiles(t){try{const d=githubRequest(githubUrl(CONFIG.GITHUB_DIR),t);return Array.isArray(d)?d.filter(x=>x.type==='file'):[]}catch(e){if(String(e).indexOf('404')>=0)return[];throw e}}
function getGithubFileSha(t,p){try{return githubRequest(githubUrl(p),t).sha||null}catch(e){if(String(e).indexOf('404')>=0)return null;throw e}}
function putGithubFile(t,n,b,sha,msg){const p=CONFIG.GITHUB_DIR+'/'+encodeURIComponent(n).replace(/%2F/g,'/'),u='https://api.github.com/repos/'+CONFIG.GITHUB_OWNER+'/'+CONFIG.GITHUB_REPO+'/contents/'+p+'?ref='+encodeURIComponent(CONFIG.GITHUB_BRANCH),q={message:msg,content:Utilities.base64Encode(b.getBytes()),branch:CONFIG.GITHUB_BRANCH};if(sha)q.sha=sha;githubRequest(u,t,{method:'put',contentType:'application/json',payload:JSON.stringify(q)})}
function putGithubText(t,p,txt,sha,msg){const u='https://api.github.com/repos/'+CONFIG.GITHUB_OWNER+'/'+CONFIG.GITHUB_REPO+'/contents/'+p+'?ref='+encodeURIComponent(CONFIG.GITHUB_BRANCH),q={message:msg,content:Utilities.base64Encode(txt,Utilities.Charset.UTF_8),branch:CONFIG.GITHUB_BRANCH};if(sha)q.sha=sha;githubRequest(u,t,{method:'put',contentType:'application/json',payload:JSON.stringify(q)})}
function deleteGithubFile(t,n,sha){const p=CONFIG.GITHUB_DIR+'/'+encodeURIComponent(n).replace(/%2F/g,'/'),u='https://api.github.com/repos/'+CONFIG.GITHUB_OWNER+'/'+CONFIG.GITHUB_REPO+'/contents/'+p+'?ref='+encodeURIComponent(CONFIG.GITHUB_BRANCH);githubRequest(u,t,{method:'delete',contentType:'application/json',payload:JSON.stringify({message:'Remove deleted On Stage photo',sha,branch:CONFIG.GITHUB_BRANCH})})}
